# All commands below are run from root directory of repository by CodeBuild
version: 0.2

env:
  variables:
    TF_VAR_region: "ap-southeast-2"
    TF_VAR_name: "audio-insights"
    TF_VAR_kms_key_arns: '["arn:aws:kms:ap-southeast-2:982898479788:key/0ec9686b-13a1-40fc-8256-86e8d3503e9c"]'
    TF_VAR_ssm_parameter_arns: '["arn:aws:ssm:ap-southeast-2:982898479788:parameter/shared/*","arn:aws:ssm:ap-southeast-2:982898479788:parameter/audio-insights/*"]'
    TF_VAR_build_docker_image: "jch254/docker-node-terraform-aws"
    TF_VAR_build_docker_tag: "latest"
    TF_VAR_buildspec: "buildspec.yml"
    TF_VAR_source_location: "https://github.com/jch254/audio-insights.git"
    TF_VAR_bucket_name: "audio-insights.603.nz"
    TF_VAR_dns_names: '["audio-insights.603.nz"]'
    TF_VAR_route53_zone_id: "Z18NTUPI1RKRGC"
    TF_VAR_acm_arn: "arn:aws:acm:us-east-1:982898479788:certificate/65811194-cc89-4926-83c3-199c5c0b6e0c"
    SPOTIFY_CALLBACK_URI: "https://audio-insights.603.nz/spotifylogincallback"
    REMOTE_STATE_BUCKET: "603-terraform-remote-state"
  parameter-store:
    SPOTIFY_CLIENT_ID: "/audio-insights/spotify-client-id"
    GA_ID: "/audio-insights/ga-id"

phases:
  install:
    commands:
      # Workaround until CodeBuild/CodePipeline retains file permissions
      - find ./infrastructure -name "*.bash" -exec chmod +x {} \;
      - ./infrastructure/install.bash

  pre_build:
    commands:
      - export SPOTIFY_SCOPES="user-top-read playlist-modify-private"

  build:
    commands:
      - ./infrastructure/build-artifacts.bash
      - ./infrastructure/deploy-infrastructure.bash
      - ./infrastructure/upload-artifacts.bash
